apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: us-central1-docker.pkg.dev/omega-palace-454013-m1/frauddetectiondemo/frauddetectservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/credentials/service-account-key.json
          volumeMounts:
            - name: credentials-volume
              mountPath: /app/credentials/service-account-key.json
              subPath: service-account-key.json
            - name: config-volume
              mountPath: /app/config/application.yml
              subPath: application.yml
            - name: rule-config-volume
              mountPath: /app/config/fraud-rules/rules-config.yml
              subPath: rules-config.yml
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: credentials-volume
          secret:
            secretName: google-credentials
        - name: config-volume
          configMap:
            name: fraud-detection-config
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
